### ISSUE TITLE
Various errata

### ISSUE THREAD

**Issue by Xyphistor** [Quantumrunner/ValkyrieCityOfTheDead#1]
[City of the Dead Errata.xlsx](https://github.com/Quantumrunner/ValkyrieCityOfTheDead/files/4848003/City.of.the.Dead.Errata.xlsx)

**Comment by Quantumrunner** [comment]
Thanks Xyphistor. I'll need some time to work trough this stuff. I'll update this post as soon as the fixes and improvements are ready.

**Comment by Quantumrunner** [comment]
All fixed. As always very helpful. Feedback. Thank you!
